---
galaxy_info:
  author: jriguera
  description: Dnsmasq server for RHEL/CentOS 6.x and Debian/Ubuntu
  company: Springer SBM
  license: GPLv3
  min_ansible_version: 1.9

  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie

  categories:
    - networking

dependencies: []
