---
- name: Debian - Import repository key
  apt_key: url="{{ ironic_os_repo_key }}" state=present
  when: >
    ansible_os_family == 'Debian' and 
    not ironic_os_packages and
    not ironic_os_repo_key is none and
    ironic_os_repo_key | search("http://.*")
  ignore_errors: yes
  tags: ["debian"]

- name: Debian - Add repository package
  apt: name="{{ ironic_os_repo_key }}" state=latest
  when: >
    ansible_os_family == 'Debian' and 
    not ironic_os_packages and
    not ironic_os_repo_key is none and
    not ironic_os_repo_key | search("http://.*")
  tags: ["debian"]

- name: Debian - Add repository url
  apt_repository: repo="{{ ironic_os_repo_url }}" state=present
  when: >
    ansible_os_family == 'Debian' 
    and not ironic_os_packages
  tags: ["debian"]

- name: RedHat - Add repository
  yum: name="{{ ironic_os_repo_url }}" state=present
  when: >
    ansible_os_family == 'RedHat' and 
    not ironic_os_packages
  tags: ["redhat"]

- name: RedHat - Import repository key
  rpm_key: key="{{ ironic_os_repo_key }}" state=present
  when: >
    ansible_os_family == 'RedHat' and 
    not ironic_os_packages and 
    not ironic_os_repo_key is none
  tags: ["redhat"]

- name: Check if configuration exists
  stat: path="{{ ironic_config_file }}"
  register: __ironic_conf

- name: Setup configuration fact
  set_fact: _ironic_previous="{{ __ironic_conf.stat.exists }}"


