---
- name: RedHat - Install Ironic-API required packages
  yum:
    name: "{{ item.key }}{{ '-' + item.version | default('*') }}"
    state: "{{ item.state | default('present') }}"
  with_dict: ironic_api_packages
  when: ansible_os_family == 'RedHat'
  register: __ironic_api_installed
  tags: ["redhat"]

- name: Debian - Install Ironic-API required packages
  apt: 
    name: "{{ item.key }}{{ '=' + item.version | default('*') }}"
    state: "{{ item.state | default('present') }}"
    install_recommends: "{{ ironic_packages_install_recommends }}"
  with_dict: ironic_api_packages
  when: ansible_os_family == 'Debian'
  register: __ironic_api_installed
  tags: ["debian"]

- name: Check if Ironic-API packages were installed
  set_fact: _ironic_api_reinstalled="{{ __ironic_api_installed.changed }}"

# Because Ubuntu starts ironic daemons as part of the install process, 
# we need to stop it
- name: Stop Ironic-API daemon after initial install
  service: name="{{ ironic_api_service_name }}" state=stopped enabled=no
  ignore_errors: yes
  when: _ironic_api_reinstalled

- name: Debian - Delete Ironic-API upstart configuration
  file:
    path: "/etc/init/{{ ironic_api_service_name }}.conf"
    state: absent
  when: >
    ansible_os_family == 'Debian' and
    ironic_init_system != "upstart"
  notify: stop api

- name: Debian - Delete Ironic-API init.d configuration
  file:
    path: "/etc/init.d/{{ ironic_api_service_name }}"
    state: absent 
  when: >
    ansible_os_family == 'Debian' and
    ironic_init_system != "initd"
  notify: stop api

# Flush all notify stop handlers, to be sure that they are done!
# The reason is because of upstart service
- meta: flush_handlers

