---
- name: RedHat - Install console packages
  yum:
    name: "{{ item.key if ('version' not in item.value) else ('%s-%s' % (item.key, item.value['version'])) }}"
    state: "{{ item.value.state | default('present') }}"
  with_dict: "{{ ironic_conductor_packages_console }}"
  when: ansible_os_family == 'RedHat'
  tags: ["install", "redhat", "packages"]

- name: Debian - Install console packages
  apt: 
    name: "{{ item.key if ('version' not in item.value) else ('%s=%s' % (item.key, item.value['version'])) }}"
    state: "{{ item.value.state | default('present') }}"
    install_recommends: "{{ ironic_packages_install_recommends }}"
  with_dict: "{{ ironic_conductor_packages_console }}"
  when: ansible_os_family == 'Debian'
  tags: ["install", "debian", "packages"]

- name: Create PIDs folder for console processes
  file:
    path: "{{ ironic_console_terminal_pid_dir }}"
    owner: "{{ ironic_user }}"
    group: "{{ ironic_group }}"
    mode: 0755
    state: directory
  when: >
    ironic_console_terminal_pid_dir is defined and
    ironic_console_terminal_pid_dir != ironic_tempdir
  tags: ["configure"]

- name: Disable shellinabox daemon
  service: name="{{ ironic_conductor_shellinabox_service_name }}" state=stopped enabled=no
  when: > 
    ironic_console_terminal is defined and 
    ironic_console_terminal == 'shellinaboxd'
  tags: ["configure"]

