---
- name: Control if the role is supported on this system
  fail: msg="Dnsmasq role is not supported on this system"
  when: >
     ansible_distribution != 'Ubuntu' and 
     ansible_distribution != 'CentOS' and 
     ansible_distribution != 'Debian' and 
     ansible_distribution != 'RedHat'

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  when: not nginx_lua
  tags: ["distribution", "packages", "service", "nginx"]

- name: Include OS specific variables for lua
  include_vars: "{{ ansible_os_family }}_lua.yml"
  when: nginx_lua
  tags: ["distribution", "packages", "service", "nginx", "lua"]

- include: install.yml
  tags: ["nginx", "install"]

- include: configure.yml
  tags: ["nginx", "configure"]

- include: server.yml
  tags: ["nginx", "server"]

