---
- name: Delete default vhost
  file:
    path: "{{ nginx_default_server_path }}"
    state: absent
  when: >
    nginx_remove_default_server
    and nginx_default_server_path is defined
    and nginx_default_server_path
  notify: reload nginx
  tags: ["delete"]


# Delete vhosts
- block:
  - name: Delete vhost definition file
    file:
      path: "{{ nginx_sites_dir }}/{{ item.name }}.conf"
      state: absent
    with_items: "{{ nginx_server_list }}"
    when: item.delete is defined and item.delete
    notify: reload nginx

  - name: Delete vhost authentication file
    file:
      path: "{{ nginx_auth_dir }}/{{ item.name }}.conf"
      state: absent
    with_items: "{{ nginx_server_list }}"
    when: item.delete is defined and item.delete

  # Delete lua files
  - name: Delete referenced lua files
    file:
      path: "{{ nginx_lua_dir }}/{{ item.1 | basename }}"
      state: absent
    when: nginx_lua and (item.0.delete is defined and item.0.delete)
    with_subelements:
      - "{{ nginx_server_list }}"
      - lua_files
      - flags:
        skip_missing: True

  - name: Delete vhost location authentication file
    file:
      path: "{{ nginx_auth_dir }}/{{ item.0.name }}_{{ item.1.name | hash('md5') }}.conf"
      state: absent
    with_subelements:
      - "{{ nginx_server_list }}"
      - location_list
      - flags:
        skip_missing: True
    when: item.0.delete is defined and item.0.delete

  when: nginx_server_list is defined and nginx_server_list
  no_log: True
  tags: ["delete"]


# Add vhosts
- block:
  - name: Create vhost servers root
    file: 
      path: "{{ item.root }}"
      state: directory
      mode: 0775
      owner: "{{ nginx_user }}"
    when: >
      not (item.delete is defined and item.delete) and
      (item.root is defined and item.root)
    with_items: "{{ nginx_server_list }}"

  - name: Create vhost servers location root
    file:
      path: "{{ item.1.root }}"
      state: directory
      mode: 0775
      owner: "{{ nginx_user }}"
    when: >
      not (item.0.delete is defined and item.0.delete) and
      (item.1.root is defined and item.1.root)
    with_subelements:
      - "{{ nginx_server_list }}"
      - location_list
      - flags:
        skip_missing: True

  - name: Create vhost authentication file
    template:
      src: auth_vhost.conf.j2
      dest: "{{ nginx_auth_dir }}/{{ item.name }}.conf"
      owner: "{{ nginx_user }}"
      group: "{{ nginx_group }}"
      mode: 0644
    when: >
      not (item.delete is defined and item.delete) and
      (item.auth is defined and item.auth)
    with_items: "{{ nginx_server_list  }}"

  - name: Create vhost location authentication file
    template:
      src: auth.conf.j2
      dest: "{{ nginx_auth_dir }}/{{ item.0.name }}_{{ item.1.name | hash('md5') }}.conf"
      owner: "{{ nginx_user }}"
      group: "{{ nginx_group }}"
      mode: 0644
    when: >
      not (item.0.delete is defined and item.0.delete) and
      (item.1.auth is defined and item.1.auth)
    with_subelements:
      - "{{ nginx_server_list }}"
      - location_list
      - flags:
        skip_missing: True

  # Copy lua files
  - name: Copy referenced lua files
    copy:
      src: "{{ item.1 }}"
      dest: "{{ nginx_lua_dir }}/{{ item.1 | basename }}"
      owner: "{{ nginx_user }}"
      group: "{{ nginx_group }}"
      mode: 0644
    when: >
      nginx_lua and
      not (item.0.delete is defined and item.0.delete)
    with_subelements:
      - "{{ nginx_server_list }}"
      - lua_files
      - flags:
        skip_missing: True
    notify: reload nginx

  - name: Add vhost servers configuration
    template:
      src: server.conf.j2
      dest: "{{ nginx_sites_dir }}/{{ item.name }}.conf"
      owner: "{{ nginx_user }}"
      group: "{{ nginx_group }}"
      mode: 0644
    when: not (item.delete is defined and item.delete)
    with_items: "{{ nginx_server_list }}"
    notify: reload nginx

  when: nginx_server_list is defined and nginx_server_list
  no_log: True
  tags: ["create"]

