---
# Enable or disable inspector daemon and pxe configuration
ironic_inspector_enabled: true
ironic_inspector_enabled_on_startup: true

ironic_inspector_debug: false
ironic_inspector_trace: false
ironic_inspector_verbose: true

ironic_inspector_listen_address: "0.0.0.0"
ironic_inspector_listen_port: 5050
ironic_inspector_timeout: 3600
ironic_inspector_node_status_keep_time: 604800
ironic_inspector_clean_up_period: 60
ironic_inspector_max_concurrency: 1000
ironic_inspector_introspection_delay: 5
ironic_inspector_log: "/var/log/ironic-inspector/inspector.log"
ironic_inspector_publish_errors: true
ironic_inspector_fatal_deprecations: false

# Define these vars for mysql connection:
#ironic_inspector_database_mysql_host: "localhost"
#ironic_inspector_database_mysql_userid: "inspector"
#ironic_inspector_database_mysql_password: "inspector"
#ironic_inspector_database_mysql_db: "inspector"
# otherwise:
ironic_inspector_database_connection: "sqlite:///var/lib/ironic-inspector/inspector.db"
ironic_inspector_database_idle_timeout: 600
ironic_inspector_database_pool_size: 10
#ironic_inspector_database_pool_timeout:
ironic_inspector_database_use_db_reconnect: true

ironic_inspector_ironic_url: "http://127.0.0.1:6385/"
ironic_inspector_ironic_os_service_type: "baremetal"
ironic_inspector_ironic_os_endpoint_type: "internalURL"

# Force download always the IPA ramdisk and kernel
ironic_inspector_ipa_force_download: false
ironic_inspector_ipa_ramdisk_url: "http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe_image-oem.cpio.gz"
ironic_inspector_ipa_kernel_url: "http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe.vmlinuz"
ironic_inspector_ipa_images_path: "/var/lib/ironic/images"
# Define ipa_kernel and ipa_initramfs to create the $TFTPROOT/pxelinux.cfg/default
# otherwise they will be donwloaded
#ironic_inspector_ipa_kernel:
#ironic_inspector_ipa_ramdisk:
ironic_inspector_ipa_callback_url: "http://{{ ansible_eth0.ipv4.address }}:{{ ironic_inspector_listen_port | default('5050') }}/v1/continue"
ironic_inspector_ipa_pxe_append_params: ["nofb", "nomodeset", "vga=normal", "coreos.autologin"]
ironic_inspector_ipa_tftproot: "/var/lib/ironic/tftpboot"

# Define auth_uri to use keystone authentication, otherwise
# noauth will be assumed
ironic_inspector_keystone_authtoken_auth_uri:
ironic_inspector_keystone_authtoken_region_name: "RegionOne"
ironic_inspector_keystone_authtoken_auth_version: 2
ironic_inspector_keystone_authtoken_delay_auth_decision: false
ironic_inspector_keystone_authtoken_identity_uri:
ironic_inspector_keystone_authtoken_service_user: "admin"
ironic_inspector_keystone_authtoken_service_password: "admin"
ironic_inspector_keystone_authtoken_service_tenant_name: "admin"

ironic_inspector_firewall_manage: false
ironic_inspector_firewall_interface: "eth0"
ironic_inspector_firewall_update_period: 15
ironic_inspector_firewall_chain: "ironic-inspector"

ironic_inspector_processing_add_ports: "pxe"
ironic_inspector_processing_keep_ports: "all"
ironic_inspector_processing_overwrite_existing: true
ironic_inspector_processing_enable_setting_ipmi_credentials: true
#ironic_inspector_processing_default_processing_hooks: ["ramdisk_error", "root_disk_selection", "scheduler", "validate_interfaces"]
#ironic_inspector_processing_processing_hooks: ["$default_processing_hooks"]
#ironic_inspector_processing_node_not_found_hook:
ironic_inspector_processing_ramdisk_logs_dir: "/var/log/ironic-inspector"
ironic_inspector_processing_always_store_ramdisk_logs: false
ironic_inspector_processing_store_data_location: "inspection"
ironic_inspector_processing_disk_partitioning_spacing: true

# If swift_os_auth_url is not none, it will be used for storing introspection data. 
# otherwise introspection data will not be stored.
ironic_inspector_swift_os_auth_url:
ironic_inspector_swift_os_auth_version: 2
ironic_inspector_swift_delete_after: 600
ironic_inspector_swift_container: "ironic-inspector"
ironic_inspector_swift_username: "admin"
ironic_inspector_swift_password:
ironic_inspector_swift_tenant_name: "admin"
ironic_inspector_swift_os_service_type: "object-store"
ironic_inspector_swift_os_endpoint_type: "internalURL"

