---
mysql_enabled_on_startup: true

# Install from upstream repos or directly from operating system packages
# except for RH/Centos -overwritten in vars files- because it has been changed
# by MariaDB
mysql_os_packages: True

# Other settings
mysql_nice: 0
mysql_performance_schema: true
mysql_init_connect: "SET NAMES utf8"
mysql_wait_timeout: 28800
mysql_root_username: "root"
mysql_root_password: "root"

# MySQL connection settings
mysql_port: 3306
mysql_bind: "0.0.0.0"

# Logging settings
mysql_log_error: "/var/log/mysql/error.log"
mysql_syslog_tag: "mysql"

# Slow query log settings
mysql_slow_query_log: false
mysql_slow_query_log_file: "/var/log/mysql/mysql-slow.log"
mysql_slow_query_time: 3

# Memory settings (default values optimized ~512MB RAM)
mysql_key_buffer_size: "256M"
mysql_max_allowed_packet: "64M"
mysql_table_open_cache: "256"
mysql_sort_buffer_size: "1M"
mysql_read_buffer_size: "1M"
mysql_read_rnd_buffer_size: "4M"
mysql_myisam_sort_buffer_size: "64M"
mysql_thread_cache_size: "8"
mysql_query_cache_size: "16M"

# InnoDB settings
# Set .._buffer_pool_size up to 80% of RAM but beware of setting too high.
mysql_innodb_file_per_table: "1"
mysql_innodb_buffer_pool_size: "256M"
# Set .._log_file_size to 25% of buffer pool size.
mysql_innodb_log_file_size: "64M"
mysql_innodb_log_buffer_size: "8M"
mysql_innodb_flush_log_at_trx_commit: "1"
mysql_innodb_lock_wait_timeout: 50

# Databases, for example:
#mysql_database_list:
#  - { name: example, collation: utf8_general_ci, encoding: utf8, replicate: 1 }

# Users, example:
#mysql_user_list:
#  - { name: example, host: 127.0.0.1, password: secret, priv: *.*:USAGE }

# Replication settings (replication is only enabled if master/user have values)
mysql_server_id: "{{ ansible_default_ipv4.address | replace('.', ', ') | list | last  }}"
mysql_max_binlog_size: "100M"
mysql_expire_logs_days: "10"
mysql_replication_role: "none"
#mysql_replication_master:

# Same keys as `mysql_users` above.
mysql_replication_user: { name: repl, host: "%", password: secret, priv: "*.*:REPLICATION SLAVE" }

# mysqldump settings
mysql_mysqldump_max_allowed_packet: "64M"

