---

# This is just an example using command module, a better way will
# be available in ansible 2.0 will be easy with the cloud modules
# http://docs.ansible.com/ansible/os_ironic_module.html

- name: Poweroff and delete servers using Ironic
  hosts: ironic
  become: True
  gather_facts: False
  vars_files:
    - vars/baremetal.yml
  vars:
      baremetal_client: "{{ groups.client[0] }}"

  vars_prompt:
    - name: "id"
      prompt: "Server Name"
      private: no

  pre_tasks:
    - name: Include network definitions
      include_vars: "servers/{{ id }}.yml"

    - include: tasks/baremetal_prepare.yml

  tasks:
    - name: List the defined servers
      shell: >
        ironic
        --os-auth-token="{{ baremetal_ironic_token }}"
        --ironic-url="{{ baremetal_server_ironic_api }}"
        node-list | awk -F '|' "/{{ baremetal_name }}/ { print \$2,\$5 }"
      register: __baremetal_new
      ignore_errors: yes
      delegate_to: "{{ baremetal_client }}"

    - name: Checking if server name exists
      fail: msg="Server name '{{ baremetal_name }}' does not exist!"
      when: __baremetal_new.stdout|trim  == ''

    - name: Power off the server
      command: >
        ironic
        --os-auth-token="{{ baremetal_ironic_token }}"
        --ironic-url="{{ baremetal_server_ironic_api }}"
        node-set-power-state "{{ baremetal_name }}" off
      when: __baremetal_new.stdout.split() | last | trim  == 'on'
      delegate_to: "{{ baremetal_client }}"

    - name: Pause half a minute
      pause: seconds=30 prompt="Giving some time to stop the server ..."
      when: __baremetal_new.stdout.split() | last | trim == 'on'
      delegate_to: "{{ baremetal_client }}"

    - name: Delete the server
      command: >
        ironic
        --os-auth-token="{{ baremetal_ironic_token }}"
        --ironic-url="{{ baremetal_server_ironic_api }}"
        node-delete "{{ baremetal_name }}"
      delegate_to: "{{ baremetal_client }}"

    - name: Delete config-drive
      file:
        path: "{{ baremetal_server_configdrive_path }}/{{ __baremetal_new.stdout.split() | first | trim }}"
        state: absent

