---
- name: Ensure package cache is up-to-date
  hosts: server
  become: yes
  serial: 1
  vars:
    _package_cache_update: true

  pre_tasks:
    # Load variables from vars instead from the inventory. This is to
    # be able to encrypt those with vault. Comment out this task in order
    # to get them from the inventory.
    - name: "Load Ironic (encrypted) variables"
      include_vars: "{{ item }}"
      with_first_found:
      - "vars/{{ deployment }}/Ironic.yml"
      - "vars/Ironic.yml"

  tasks:
    - include: tasks/package_cache_update.yml

- name: MySQL database setup
  hosts: database
  become: yes
  roles:
  - role: mysql
  - role: monit

- name: RabbitMQ messaging setup
  hosts: messaging
  become: yes
  roles:
  - role: rabbitmq
  - role: monit

- name: Ironic API setup
  hosts: ironic-api
  become: yes
  roles:
  - role: ironic
  - role: inspector
    ironic_inspector_discovery_enroll_dir: "vars/{{ deployment }}/inspector"
  - role: nginx
  - role: webclient
  - role: monit

- name: Ironic Conductor setup
  hosts: ironic-conductor
  become: yes
  roles:
  - role: ironic
  - role: dnsmasq
  - role: monit

