---
# Database server
- hosts: database
  sudo: true
  roles:
    - role: mysql
    - role: monit

# RabbitMQ server
- hosts: messaging
  sudo: true
  roles:
    - role: rabbitmq
    - role: monit

# Ironic API server
- hosts: ironic-api
  sudo: true
  roles:
    - role: ironic
    - role: monit

# Ironic Conductor with http repo
# HTTP can be centralized on the API if you use IPA
- hosts: ironic-conductor
  sudo: true
  roles:
    - role: ironic
    - role: dnsmasq
    - role: nginx
    - role: monit
