---
- hosts: all
  sudo: true
  vars:
    baremetal_server_database_rootpass: root
    baremetal_server_database_name: ironic
    baremetal_server_database_user: ironic
    baremetal_server_database_pass: mysql
    baremetal_server_inspector_database_name: inspector
    baremetal_server_inspector_database_user: inspector
    baremetal_server_inspector_database_pass: mysql
    baremetal_server_msg_vhost: ironic
    baremetal_server_msg_user: ironic
    baremetal_server_msg_pass: rabbitmq
    baremetal_server_dhcp_params: ["10.0.1.100", "10.0.1.200", "infinite"]
    baremetal_server_dhcp_domain: pxe.local
    baremetal_server_http_root_path: /var/lib/ironic/http
    baremetal_server_images_path: /var/lib/ironic/http/images
    baremetal_server_images_deploy_path: /var/lib/ironic/http/deploy

  roles:
    - role: mysql
      mysql_root_password: "{{ baremetal_server_database_rootpass }}"
      mysql_database_list:
        - name: "{{ baremetal_server_database_name }}"
        - name: "{{ baremetal_server_inspector_database_name }}"
      mysql_user_list:
        - name: "{{ baremetal_server_database_user }}"
          password: "{{ baremetal_server_database_pass }}"
          priv: "{{ baremetal_server_database_name }}.*:ALL"
          host: "%"
        - name: "{{ baremetal_server_inspector_database_user }}"
          password: "{{ baremetal_server_inspector_database_pass }}"
          priv: "{{ baremetal_server_inspector_database_name }}.*:ALL"
          host: "%"

    - role: rabbitmq
      rabbitmq_vhost_definition_list:
        - name: "{{ baremetal_server_msg_vhost }}"
      rabbitmq_users_definition_list:
        - user: "{{ baremetal_server_msg_user }}"
          password: "{{ baremetal_server_msg_pass }}"
          vhost: "{{ baremetal_server_msg_vhost }}"
          tags: [ "administrator", "management" ]

    - role: ironic
      ironic_debug: true
      ironic_my_ip: "{{ ansible_eth0.ipv4.address }}"
      ironic_conductor_api_url: "http://{{ ansible_eth0.ipv4.address }}:6385/"
      ironic_pxe_tftp_server: "{{ ansible_eth1.ipv4.address }}"
      ironic_oslo_messaging_rabbit_host: "localhost"
      ironic_oslo_messaging_rabbit_userid: "{{ baremetal_server_msg_user }}"
      ironic_oslo_messaging_rabbit_password: "{{ baremetal_server_msg_pass }}"
      ironic_oslo_messaging_rabbit_virtual_host: "{{ baremetal_server_msg_vhost }}"
      ironic_database_mysql_host: "localhost"
      ironic_database_mysql_userid: "{{ baremetal_server_database_user }}"
      ironic_database_mysql_password: "{{ baremetal_server_database_pass }}"
      ironic_database_mysql_db: "{{ baremetal_server_database_name }}"
      ironic_pxe_images_path: "{{ baremetal_server_images_path }}"
      ironic_pxe_append_params: ["nofb", "nomodeset", "vga=normal", "coreos.autologin"]
      ironic_deploy_http_url: "http://{{ ansible_eth1.ipv4.address }}/deploy"
      ironic_deploy_http_root: "{{ baremetal_server_images_deploy_path }}"
      ironic_deploy_erase_devices_priority: 0
      ironic_enabled_drivers: ["pxe_ipmitool", "agent_ipmitool"]

    - role: ironic-inspector
      ironic_inspector_ironic_url: "http://{{ ansible_eth0.ipv4.address }}:6385/"
      ironic_inspector_database_mysql_host: "localhost"
      ironic_inspector_database_mysql_userid: "{{ baremetal_server_inspector_database_user }}"
      ironic_inspector_database_mysql_password: "{{ baremetal_server_inspector_database_pass }}"
      ironic_inspector_database_mysql_db: "{{ baremetal_server_inspector_database_name }}"

    - role: dnsmasq
      dnsmasq_conf_domain: "{{ baremetal_server_dhcp_domain }}"
      dnsmasq_conf_dhcp:
        eth0:
          range: "{{ baremetal_server_dhcp_params }}"
          ignore_names: true
          generate_names: true
          option:
            - "option:router,{{ ansible_default_ipv4.gateway }}"
            - "option:dns-server,{{ ansible_eth0.ipv4.address }}"
          boot: [ "{{ ironic_pxe_bootfile_name }}" ]
          tftp: "{{ ironic_pxe_tftp_root }}"

    - role: nginx
      nginx_server_list:
        - name: "{{ ansible_hostname }}"
          root: "{{ baremetal_server_http_root_path }}"
          access_log: "/var/log/nginx/{{ ansible_hostname }}-server_access.log"
          location_list:
            - name: "/"
              autoindex: "on"

    - role: monit
      monit_monitoring_list:
        - name: mysql
          type: process
          target: "{{ mysql_pidfile }}"
          start:
            script: "/etc/init.d/mysql start"
            timeout: 60
          stop: 
            script: "/etc/init.d/mysql stop"
        - name: rabbitmq
          type: process
          target: "{{ rabbitmq_pidfile }}"
          start: 
            script: "/etc/init.d/rabbitmq-server start"
          stop:
            script: "/etc/init.d/rabbitmq-server stop"
        - name: dnsmasq
          type: process
          target: "{{ dnsmasq_pidfile }}"
          start:
            script: "/etc/init.d/dnsmasq start"
          stop:
            script: "/etc/init.d/dnsmasq stop"
        - name: ironic-api
          type: process
          target: "{{ ironic_api_pidfile }}"
          start:
            script: "/usr/sbin/service ironic-api start"
          stop:
            script: "/usr/sbin/service ironic-api stop"
        - name: ironic-conductor
          type: process
          target: "{{ ironic_conductor_pidfile }}"
          start: 
            script: "/usr/sbin/service ironic-conductor start"
          stop: 
            script: "/usr/sbin/service ironic-conductor stop"
        - name: nginx
          type: process
          target: "{{ nginx_pidfile }}"
          start:
            script: "/etc/init.d/nginx start"
          stop:
            script: "/etc/init.d/nginx stop"

  tasks:

    - name: Create configdrive metadata folder
      file:
        path: "{{ baremetal_server_http_root_path }}/metadata"
        mode: 0755
        recurse: yes
        state: directory

    - name: Download IPA Coreos ramdisk
      get_url:
        url: http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe_image-oem.cpio.gz
        dest: "{{ baremetal_server_images_deploy_path }}/coreos_production_pxe_image-oem.cpio.gz"
        force: no

    - name: Download IPA Coreos kernel
      get_url:
        url: http://tarballs.openstack.org/ironic-python-agent/coreos/files/coreos_production_pxe.vmlinuz
        dest: "{{ baremetal_server_images_deploy_path }}/coreos_production_pxe.vmlinuz"
        force: no
  
#   - name: Display all variables/facts known for a host
#     debug: var=hostvars[inventory_hostname]

