---
- hosts: all
  sudo: true
  vars:
    baremetal_server_database_rootpass: root
    baremetal_server_database_name: ironic
    baremetal_server_database_user: ironic
    baremetal_server_database_pass: mysql
    baremetal_server_msg_vhost: ironic
    baremetal_server_msg_user: ironic
    baremetal_server_msg_pass: rabbitmq
    baremetal_server_dhcp_params: ["10.0.1.100", "10.0.1.200", "infinite"]
    baremetal_server_dhcp_domain: pxe.local
    baremetal_server_http_root_path: /var/lib/ironic/http
    baremetal_server_images_path: /var/lib/ironic/http/images
    baremetal_server_metadata_path: /var/lib/ironic/http/metadata
    baremetal_server_images_deploy_path: /var/lib/ironic/http/deploy

  roles:

    - role: nginx
      nginx_server_list:
        - name: "{{ ansible_hostname }}"
          root: "{{ baremetal_server_http_root_path }}"
          client_body_temp_path: "{{ baremetal_server_http_root_path }}/tmp"
          access_log: "/var/log/nginx/{{ ansible_hostname }}-server_access.log"
          location_list:
            - name: "/"
              autoindex: "on"
            - name: "/images/"
              autoindex: "on"
              client_body_buffer_size: "16k" 
              client_max_body_size: "50G"
              create_full_put_path: "on"
              dav_access: "user:rw group:rw all:r"
              dav_methods: "PUT DELETE MKCOL COPY MOVE"
              default_type: "application/octet-stream"
              client_body_temp_path: "{{ baremetal_server_http_root_path }}/tmp"
              auth:
                title: "Restricted"
                users:
                  jose: "$apr1$g6dhYrSM$kgYM/qx/knhg4Nz8C9W9A."
            - name: "/metadata/"
              autoindex: "on"
              client_body_buffer_size: "16k" 
              client_max_body_size: "100M"
              create_full_put_path: "on"
              dav_access: "user:rw group:rw all:r"
              dav_methods: "PUT DELETE MKCOL COPY MOVE"
              default_type: "application/octet-stream"
              client_body_temp_path: "{{ baremetal_server_http_root_path }}/tmp"

#  tasks:  
#   - name: Display all variables/facts known for a host
#     debug: var=hostvars[inventory_hostname]

