---
- name: Delete monitors
  file: path="{{ monit_config_dir }}/{{ item.name }}" state=absent
  with_items: "{{ monit_monitoring_list }}"
  when: >
    monit_monitoring_list is defined and
    not monit_monitoring_list is none and
    (item.delete is defined and item.delete)
  notify: reload monit

- name: Add monitors
  template:
    src: monitor.j2
    dest: "{{ monit_config_dir }}/{{ item.name }}"
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    mode: 0644
  with_items: "{{ monit_monitoring_list }}"
  when: >
    monit_monitoring_list is defined and
    not monit_monitoring_list is none and
    not (item.delete is defined and item.delete)
  notify: reload monit

