---
- name: Create default system monitor
  template:
    src: system.j2
    dest: "{{ monit_config_dir }}/{{ ansible_hostname }}"
    owner: "{{ monit_user }}"
    group: "{{ monit_group }}"
    mode: 0644
  when: monit_monitoring_system
  notify: reload monit


- block:
  - name: Delete monitors
    file:
      path: "{{ monit_config_dir }}/{{ item.name }}"
      state: absent
    when: item.delete is defined and item.delete
    with_items: "{{ monit_monitoring_list }}"
    notify: reload monit

  - name: Delete monitors from list
    lineinfile:
      dest: "{{ monit_ansible_monitors_file }}"
      regexp: "^{{ item.name }}"
      state: absent
    when: item.delete is defined and item.delete
    with_items: "{{ monit_monitoring_list }}"

  - name: Add monitors
    template:
      src: monitor.j2
      dest: "{{ monit_config_dir }}/{{ item.name }}"
      owner: "{{ monit_user }}"
      group: "{{ monit_group }}"
      mode: 0644
    when: not (item.delete is defined and item.delete)
    with_items: "{{ monit_monitoring_list }}"
    notify: reload monit

  - name: Add monitor to list
    lineinfile:
      dest: "{{ monit_ansible_monitors_file }}"
      regexp: "^{{ item.name }}"
      line: "{{ item.name }}"
      state: present
    when: not (item.delete is defined and item.delete)
    with_items: "{{ monit_monitoring_list }}"

  when: monit_monitoring_list

