---
dnsmasq_pidfile: /var/run/dnsmasq/dnsmasq.pid

dnsmasq_user: "{{ 'root' if (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7') else 'nobody' }}"
dnsmasq_group: "{{ 'root' if (ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7') else 'nobody' }}"

dnsmasq_packages:
  dnsmasq:
    state: latest
