---
# Debian repository
- block:
  - name: Debian - Import repository key
    apt_key: url="{{ rabbitmq_os_repo_key }}" state=present
    when: >
      not rabbitmq_os_repo_key is none and
      rabbitmq_os_repo_key | search("http://.*")
    ignore_errors: yes

  - name: Debian - Add repository package
    apt: name="{{ rabbitmq_os_repo_key }}" state=latest
    when: >
      not rabbitmq_os_repo_key is none and
      not rabbitmq_os_repo_key | search("http://.*")

  - name: Debian - Add repository url
    apt_repository: repo="{{ rabbitmq_os_repo_url }}" state=present

  when: >
    ansible_os_family == 'Debian' 
    and not rabbitmq_os_packages
  tags: ["debian", "repository"]


# RedHat repository
- block:
  - name: RedHat - Add repository
    yum: name="{{ rabbitmq_os_repo_url }}" state=present

  - name: RedHat - Import repository key
    rpm_key: key="{{ rabbitmq_os_repo_key }}" state=present
    when: rabbitmq_os_repo_key is not none

  when: >
    ansible_os_family == 'RedHat' and 
    not rabbitmq_os_packages
  tags: ["redhat", "repository"]


- name: Check if configuration exists
  stat: path="{{ rabbitmq_config }}"
  register: __rabbitmq_conf

- name: Setup configuration fact
  set_fact: _rabbitmq_previous="{{ __rabbitmq_conf.stat.exists }}"

- name: RedHat - Install required packages
  yum:
    name: "{{ item.key if ('version' not in item.value) else ('%s-%s' % (item.key, item.value['version'])) }}"
    state: "{{ item.value.state | default('present') }}"
    update_cache: "{{ rabbitmq_packages_update_cache | ternary('yes', 'no') }}"
  with_dict: "{{ rabbitmq_packages }}"
  when: ansible_os_family == 'RedHat'
  register: __rabbitmq_installed_rh
  tags: ["redhat", "packages"]

- name: Debian - Install required packages
  apt: 
    name: "{{ item.key if ('version' not in item.value) else ('%s=%s' % (item.key, item.value['version'])) }}"
    state: "{{ item.value.state | default('present') }}"
    install_recommends: "{{ rabbitmq_packages_install_recommends }}"
    update_cache: "{{ rabbitmq_packages_update_cache | ternary('yes', 'no') }}"
    cache_valid_time: "{{ rabbitmq_packages_update_cache }}"
  with_dict: "{{ rabbitmq_packages }}"
  when: ansible_os_family == 'Debian'
  register: __rabbitmq_installed_debian
  tags: ["debian", "packages"]

- name: Check if packages were installed
  set_fact: _rabbitmq_reinstalled="{{ __rabbitmq_installed_rh.changed or __rabbitmq_installed_debian.changed }}"

# Because Ubuntu starts RabbitMQ as part of the install process, we need to stop it
- name: Ensure RabbitMQ is stopped after initial install
  service: name="{{ rabbitmq_daemon }}" state=stopped enabled=no
  when: _rabbitmq_reinstalled
  ignore_errors: yes

- name: Get init system
  command: cat /proc/1/comm
  register: __rabbitmq_init_system
  changed_when: False

- name: Set init system
  set_fact: rabbitmq_init_system="{{ __rabbitmq_init_system.stdout }}"

- block:
  - name: Create custom systemd folder configuration
    file:
      path: "/etc/systemd/system/{{ rabbitmq_daemon }}.service.d"
      state: directory
      mode: 0755

  - name: Define custom systemd properties
    template:
      src: systemd.conf.j2
      dest: "/etc/systemd/system/{{ rabbitmq_daemon }}.service.d/service.conf"
      mode: 0644
    register: __rabbitmq_systemd

  - name: Create pid folder
    file:
      path: "{{ rabbitmq_pidfile | dirname }}"
      owner: "{{ rabbitmq_user }}"
      group: "{{ rabbitmq_group }}"
      mode: 0775
      state: directory

  - name: Reload systemd
    command: systemctl daemon-reload
    when: __rabbitmq_systemd|changed

  when: rabbitmq_init_system == 'systemd'
  tags: ["systemd", "init"]


