---
- name: Remove guest user (hostname)
  rabbitmq_user:
    user: guest
    vhost: /
    node: "rabbit@{{ ansible_hostname }}"
    state: absent
  register: __rabbitmq_rm_guest_hostname
  when: rabbitmq_secure
  ignore_errors: true
  tags: ["rabbitmq", "vhost", "secure"]

- name: Remove guest user (default)
  rabbitmq_user:
    user: guest
    vhost: /
    state: absent
  when: rabbitmq_secure and __rabbitmq_rm_guest_hostname|failed
  tags: ["rabbitmq", "vhost", "secure"]

- name: Add vhosts
  rabbitmq_vhost:
    name: "{{ item.name }}"
    node: "{{ item.node | default('rabbit') }}"
    tracing: "{{ item.tracing | default('no') }}"
    state: present
  with_items: rabbitmq_vhost_definition_list
  when: rabbitmq_vhost_definition_list is defined
  tags: ["rabbitmq", "vhost"]

- name: Add users and setup priveleges
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost | default('/', false) }}"
    node: "{{ item.node | default('rabbit') }}"
    tags: "{{ (item.tags | default('')) | join(',') }}"
    configure_priv: "{{ item.configure_priv | default('.*') }}"
    read_priv: "{{ item.read_priv | default('.*') }}"
    write_priv: "{{ item.write_priv | default('.*') }}"
    state: present
    force: "{{ item.force|default('yes') }}"
  with_items: rabbitmq_users_definition_list
  when: rabbitmq_users_definition_list is defined
  tags: ["rabbitmq", "vhost"]


