---
galaxy_info:
  author: geerlinggy, jriguera
  description: MySQL server for RHEL/CentOS and Debian/Ubuntu (based on geerlingguy)
  company: Springer SBM
  license: GPLv3
  min_ansible_version: 1.9

  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie

  categories:
    - database
    - database:sql

dependencies: []
