---
ironic_release: "mitaka"
ironic_os_repo_url:
ironic_os_repo_key:

ironic_conductor_service_name: ironic-conductor
ironic_conductor_pidfile: /var/run/ironic/ironic-conductor.pid
ironic_conductor_shellinabox_service_name: shellinabox

ironic_api_service_name: ironic-api
ironic_api_pidfile: /var/run/ironic/ironic-api.pid

ironic_user: ironic
ironic_group: ironic

ironic_config_file: /etc/ironic/ironic.conf
ironic_config_dir: /etc/ironic/
ironic_var_dir: /var/lib/ironic/

ironic_syslinux_basedir: /var/lib/ironic/pxeutils
ironic_pxe_syslinux_version: "6.03"
ironic_pxe_syslinux_tarball_checksum: "sha1:d215372c664109258dbc18b64e699afe1a4aaedd"
ironic_pxe_syslinux_tarball_url: "https://www.kernel.org/pub/linux/utils/boot/syslinux/syslinux-6.03.tar.gz"
ironic_pxe_elilo_version: "3.16"
ironic_pxe_elilo_tarball_url: "http://heanet.dl.sourceforge.net/project/elilo/elilo/elilo-3.16/elilo-3.16-all.tar.gz"
ironic_pxe_elilo_tarball_checksum: "sha1:bd0bd4f1b3dc2d23a304f957ffbf907ae104f323"

