---
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ["distribution", "packages", "service", "mysql"]

- include: install.yml
  tags: ["mysql", "install"]

- include: configure.yml
  tags: ["mysql", "configure"]

- include: secure.yml
  tags: ["mysql", "secure"]

- include: upgrade.yml
  tags: ["mysql", "upgrade"]

- include: databases.yml
  tags: ["mysql", "databases"]

- include: users.yml
  tags: ["mysql", "users"]

- include: replication_master.yml
  when: >
    (mysql_replication_role == 'master')
    and mysql_replication_master is defined
    and mysql_replication_master is not none
  tags: ["mysql", "replication", "master"]

- include: replication_slave.yml
  when: >
    (mysql_replication_role == 'slave')
    and mysql_replication_master is defined
    and mysql_replication_master is not none
  tags: ["mysql", "replication", "slave"]

