---
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ["distribution", "packages", "service", "mysql"]

- include: install.yml
  tags: ["mysql", "install"]

- include: configure.yml
  tags: ["mysql", "configure"]

- include: secure.yml
  tags: ["mysql", "secure"]

- include: databases.yml
  tags: ["mysql", "databases"]

- include: users.yml
  tags: ["mysql", "users"]

- include: replication.yml
  tags: ["mysql", "replication"]

