---
# Run it when it was re(installed) or upgraded

- name: Running mysql_upgrade checks
  command: mysql_upgrade --protocol=SOCKET --socket="{{ mysql_socket }}" --password="{{ mysql_root_password }}" --force
  when: _mysql_reinstalled and mysql_upgrade_on_reinstall

