---
- name: Create users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    state: present
  with_items: "{{ mysql_user_list }}"
  when: mysql_user_list is defined
  no_log: True

