---
- name: restart inspector
  service: name="{{ ironic_inspector_service_name }}" state=restarted

- name: reload inspector
  service: name="{{ ironic_inspector_service_name }}" state=reloaded

- name: start inspector
  service: name="{{ ironic_inspector_service_name }}" state=started

- name: stop inspector
  service: name="{{ ironic_inspector_service_name }}" state=stopped

