---
- name: restart dnsmasq
  service: name={{ dnsmasq_daemon }} state=restarted
  
- name: reload dnsmasq
  command: killall -s HUP {{ dnsmasq_daemon }}
  
- name: start dnsmasq
  service: name={{ dnsmasq_daemon }} state=started

- name: stop dnsmasq
  service: name={{ dnsmasq_daemon }} state=stopped
  

