---
galaxy_info:
  author: Jose Riguera Lopez (jriguera@gmail.com)
  description: Install and setup ironic_webclient web app
  license: Apache 2.0
  min_ansible_version: 2.0
  
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: EL
    versions:
    - all

  categories:
    - web
    - openstack

dependencies: []

