---
rabbitmq_enabled_on_startup: True

# Install from upstream repos or directly from operating system packages
rabbitmq_os_packages: False
rabbitmq_packages_install_recommends: True
# Upgrade the database if older than these seconds
# Time is only valid in Debian, set to 0/False to disable
rabbitmq_packages_update_cache: 0

# Main options
rabbitmq_ssl: False
rabbitmq_env: True
rabbitmq_secure: True

# Avoid setting up federation
rabbitmq_federate: False
rabbitmq_federation_plugin: "rabbitmq_federation"
rabbitmq_federation_configuration_list:
rabbitmq_policy_configuration_list:

# RabbitMQ TCP configuration
rabbitmq_tcp_address: "0.0.0.0"
rabbitmq_tcp_port: 5672

# Other options:
rabbitmq_conf_reverse_dns_lookups: False
rabbitmq_conf_auth_mechanisms: ["PLAIN", "AMQPLAIN"]
rabbitmq_conf_delegate_count: 16

# RabbitMQ SSL configuration
rabbitmq_ssl_address: "0.0.0.0"
rabbitmq_ssl_port: 5671
rabbitmq_ssl_fail_if_no_peer_cert: True
rabbitmq_ssl_cacertfile: 
rabbitmq_ssl_certfile: 
rabbitmq_ssl_keyfile: 

# Plugins
#rabbitmq_plugins_dict: { plugin2: src.ez }
rabbitmq_plugins_dict: { rabbitmq_management: }
rabbitmq_plugins_only_listed: False
rabbitmq_plugins_disabled: []

# VHOST
rabbitmq_vhost_definition_list: []
rabbitmq_users_definition_list: []

# Env variables
#rabbitmq_env_dict:

