---

- block:
  - name: Downloading IPA Coreos ramdisk (~250 MB)
    get_url:
      checksum: "{{ ironic_inspector_ipa_ramdisk_checksum }}"
      url: "{{ ironic_inspector_ipa_ramdisk_url }}"
      dest: "{{ ironic_inspector_ipa_deploy_path }}/{{ ironic_inspector_ipa_ramdisk }}"
    
  - name: Downloading IPA Coreos kernel (~25 MB)
    get_url:
      checksum: "{{ ironic_inspector_ipa_kernel_checksum }}"
      url: "{{ ironic_inspector_ipa_kernel_url }}"
      dest: "{{ ironic_inspector_ipa_deploy_path }}/{{ ironic_inspector_ipa_kernel }}"

  - name: Change permissions
    file:
      path: "{{ item }}"
      owner: "{{ ironic_inspector_pxe_owner }}"
      group: "{{ ironic_inspector_pxe_group }}"
      mode: 0664
      state: file
    with_items:
      - "{{ ironic_inspector_ipa_deploy_path }}/{{ ironic_inspector_ipa_ramdisk }}"
      - "{{ ironic_inspector_ipa_deploy_path }}/{{ ironic_inspector_ipa_kernel }}"

  when: ironic_inspector_ipa_download


# When the IPA images are on a different folder we have to link it
- name: Create a link to the IPA image in the tfpboot folder
  file:
    path: "{{ ironic_inspector_ipa_tftproot }}/{{ item }}"
    src: "{{ ironic_inspector_ipa_deploy_path }}/{{ item }}"
    owner: "{{ ironic_inspector_pxe_owner }}"
    group: "{{ ironic_inspector_pxe_group }}"
    state: link
  with_items:
      - "{{ ironic_inspector_ipa_ramdisk }}"
      - "{{ ironic_inspector_ipa_kernel }}"
  when: ironic_inspector_ipa_deploy_path != ironic_inspector_ipa_tftproot


- block:
  - name: Create tftproot folder
    file:
      path: "{{ ironic_inspector_ipa_tftproot }}/pxelinux.cfg"
      owner: "{{ ironic_inspector_pxe_owner }}"
      group: "{{ ironic_inspector_pxe_group }}"
      mode: 0775
      state: directory

  - name: Generate pxelinux.cfg/default
    template:
      src: pxelinux_default.j2
      dest: "{{ ironic_inspector_ipa_tftproot }}/pxelinux.cfg/default"
      owner: "{{ ironic_inspector_pxe_owner }}"
      group: "{{ ironic_inspector_pxe_group }}"
      mode: 0664
    when: ironic_inspector_enabled

  when: >
    ironic_inspector_ipa_tftproot is not none
    and ironic_inspector_discovery_enroll

# Out of the block to be able to disable it
- name: Delete pxelinux.cfg/default
  file: dest="{{ ironic_inspector_ipa_tftproot }}/pxelinux.cfg/default" state=absent
  when: >
    ironic_inspector_ipa_tftproot is not none
    and not ironic_inspector_enabled

