---
- name: Create global resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  notify: reload dnsmasq
  tags: ["dnsmasq", "resolvconf"]
 
