---
mysql_daemon: mysql
mysql_config_file: /etc/mysql/my.cnf
mysql_socket: /var/run/mysqld/mysqld.sock
mysql_pidfile: /var/run/mysqld/mysqld.pid
mysql_packages_install_recommends: true
mysql_init_system: "initd"

mysql_packages_dict:
  mysql-common:
    state: latest
  mysql-server:
    state: latest
  python-mysqldb:
    state: latest

