---
- name: restart mysql
  service:
    name: "{{ mysql_daemon }}"
    state: restarted

- name: start mysql
  service:
    name: "{{ mysql_daemon }}"
    state: started

- name: stop mysql
  service:
    name: "{{ mysql_daemon }}"
    state: stopped
  
- name: reload mysql
  service:
    name: "{{ mysql_daemon }}"
    state: reloaded
