---
rabbitmq_os_repo_url: "http://rdo.fedorapeople.org/openstack-{{ rabbitmq_repo_release }}/rdo-release-{{ rabbitmq_repo_release }}.rpm"
rabbitmq_os_repo_key:
#rabbitmq_os_repo_url: "http://download.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
#rabbitmq_os_repo_key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"

rabbitmq_packages:
  libselinux-python:
    state: latest
  erlang:
    state: latest
  rabbitmq-server:
    state: latest
